# Generated by Django 2.1.3 on 2018-11-21 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libmgmt', '0003_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pub_date',
            field=models.DateField(null=True),
        ),
    ]
