# Generated by Django 2.1.3 on 2018-11-21 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libmgmt', '0005_publicationhouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publication',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='libmgmt.PublicationHouse'),
        ),
    ]
