# Generated by Django 2.1.3 on 2018-11-29 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libmgmt', '0007_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
