# Generated by Django 2.1.3 on 2018-11-29 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libmgmt', '0008_book_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='books_issued',
            field=models.ManyToManyField(to='libmgmt.Book'),
        ),
    ]
